
export default [
    {
        id: 1,
        title: "VERTICAL STRIPED SHIRT",
        description: "This shirt is a great choice for any occasion.",
        price: 136,
        producttype:"shirts",
        img: "product-1.svg",
        img1:"product-1.svg",
        img2:"product-1.svg",
        rating: 4,
        dress:"Casual",
        size:"X-Large",
        reviewCount: "4/5",
        openSpots: 0,
        perOff: 0
  },
    {
        id: 2,
        title: "COURAGE GRAPHIC T-SHIRT",
        description: "This shirt is a great choice for any occasion.",
        price: 125,
        dress:"Gym",
        previousPrice: 260,
        dress:"Formal",
        producttype:"t-shirts",
        img: "product-2.svg",
        img1:"product-2.svg",
        img2:"product-2.svg",
        rating: 3,
        size:"medium",
        reviewCount: "4/5",
        openSpots: 27,
        perOff: 10
    },
    {
        id: 3,
        title: "LOOSE FIT BERMUDA SHORTS",
        description: "This shirt is a great choice for any occasion.",
        price: 125,
        producttype:"shorts",
        dress:"Gym",
        previousPrice: 260,
        img: "product-3.svg",
        img1:"product-3.svg",
        img2:"product-3.svg",
        rating: 3,
        size:"X-Small",
        reviewCount: "4/5",
        openSpots: 27,
        perOff: 10
    },
    {
        id: 4,
        title: "FADED SKINNY JEANS",
        description: "This shirt is a great choice for any occasion.",
        price: 125,
        producttype:"jeans",
        dress:"Formal",
        previousPrice: 260,
        img: "product-4.svg",
        img1:"product-4.svg",
        img2:"product-4.svg",
        rating: 3,
        size:"XX-Small",
        reviewCount: "4/5",
        openSpots: 27,
        perOff: 10
    },
    {
        id: 5,
        title: "One Life Graphic T-shirt",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 50,
        producttype:"t-shirts",
        dress:"casual",
        previousPrice: 160,
        img: "product-5.svg",
        img1:"product-5-1.svg",
        img2:"product-5-2.svg",
        rating: 4,
        size:"X-Small",
        reviewCount: "4/5",
        perOff: 20

    },
    {
        id: 6,
        title: "Gradient Graphic T-shirt",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 140,
        dress:"Party",
        previousPrice: 160,
        img: "product-6.svg",
        img1:"product-6.svg",
        img2:"product-6.svg",
        rating: 4,
        size:"medium",
        reviewCount: "4/5",
        perOff: 20

    },
    {
        id: 7,
        title: "Polo with Tipping Details",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 180,
        dress:"formal",
        previousPrice: 200,
        producttype:"t-shirts",
        img: "product-7.svg",
        img1:"product-7.svg",
        img2:"product-7.svg",
        rating: 4,
        size:"medium",
        reviewCount: "4/5",
        perOff: 20

    },
    {
        id: 8,
        title: "Black Striped T-shirt",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 120,
        dress:"causal",
        previousPrice: 150,
        img: "product-8.svg",
        img1:"product-8.svg",
        img2:"product-8.svg",
        rating: 4,
        size:"Small",
        reviewCount: "4/5",
        producttype:"t-shirts",
        perOff: 20

    },
    {
        id: 9,
        title: "Checkered Shirt",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 70,
        dress:"Formal",
        previousPrice: 80,
        producttype:"shirts",
        img: "product-9.svg",
        img1:"product-9.svg",
        img2:"product-9.svg",
        rating: 4,
        size:"XX-Large",
        reviewCount: "4/5",
        perOff: 20

    },
    {
        id: 10,
        title: "SLEEVE STRIPED T-SHIRT",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 130,
        dress:"Formal",
        previousPrice: 160,
        img: "product-10.svg",
        img1:"product-10.svg",
        img2:"product-10.svg",
        rating: 4,
        size:"Large",
        producttype:"t-shirts",
        reviewCount: "4/5",
        perOff: 20

    },
    {
        id: 11,
        title: "marshmellow hoodie",
        description: "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        price: 5000,
        dress:"Party",
        previousPrice: 160,
        producttype:"hoodie",
        img: "product-11.svg",
        img1:"product-11.svg",
        img2:"product-11.svg",
        rating: 4,
        size:"3X-Large",
        reviewCount: "4/5",
        perOff: 20

    }
]